version: '3.9'
services:
  web:
    build: 
      context: ./docker
      dockerfile: Dockerfile
    ports:
      - "8069:${ODOO_PORT}"
      - "8072:8072"
    volumes:
      - './addons:/mnt'
      - './config:/etc/odoo'
      - './odoo:/odoo'
    networks:
      - default
    tty: true
    logging:
      driver: "json-file"
      options:
        max-size: "200m"
    depends_on:
      - db
    env_file: '.env'
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - ODOO_PASSWORD=${ODOO_PASSWORD}
    command: /odoo/odoo-bin --c /etc/odoo/odoo.conf --db_host db --db_port ${POSTGRES_PORT} --db_user ${POSTGRES_USER} --db_password ${POSTGRES_PASSWORD}

  db:
    image: 'postgres:latest'
    restart: always
    ports:
      - '5432:${POSTGRES_PORT}'
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - PGPASS=${POSTGRES_PASSWORD}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - 'postgres-data:/var/lib/postgresql/data/pgdata'
    networks:
      - default
    logging:
      driver: json-file
      options:
        max-size: 20m
    env_file: '.env'

volumes:
  postgres-data: null
  odoo-data: null
